# Auto re-apply IR emitter when IR camera appears (boot, resume, lid-open).
# Generated by the face.howdy plugin — do not edit manually.
ACTION=="add", SUBSYSTEM=="video4linux", ATTRS{idVendor}=="CHANGEME_VENDOR", ATTRS{idProduct}=="CHANGEME_PRODUCT", TAG+="systemd", ENV{SYSTEMD_WANTS}="ir-emitter.service"
